name: Picture Warehouse CI

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
  schedule:
    # 北京时间23点对应UTC时间15点
    - cron:  '0 15 * * *'

jobs:
  run_python_script_actions:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements.txt

      - name: current date
        run: date

      - name: Run main.py
        run: python main.py

      - name: Commit Change files
        run: |
           git config --local user.email "huangzhendong1996@163.com"
           git config --local user.name "Zander"
           git pull
           git add .
           git commit -m "Picture Warehouse CI Update"

      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.REPOSITORY_ACTIONS_TOKEN }}
           branch: master
